import {AfterViewInit, Component, ViewChild} from '@angular/core';
import {MatTableDataSource} from "@angular/material/table";
import {MatPaginator} from "@angular/material/paginator";
import {ICliente} from "../../interfaces/ICliente";
import {MatSort} from "@angular/material/sort";

@Component({
  selector: 'app-customers',
  templateUrl: './customers.component.html',
  styleUrls: ['./customers.component.scss']
})
export class CustomersComponent implements AfterViewInit {
  displayedColumns: string[] = [
    'ragioneSociale',
    'indirizzo',
    'localita',
    'cap',
    'provincia',
    'paese',
    'piva',
    'codiceFiscale',
    'codiceSdi',
    'destionazioneMerce',
    'agenteRiferimento',
    'telefono',
    'email',
    'actions'
  ];
  dataSource = new MatTableDataSource<ICliente>(ELEMENT_DATA);

  @ViewChild(MatPaginator) paginator: MatPaginator | undefined;
  @ViewChild(MatSort) sort: MatSort | undefined;

  constructor() {
    this.dataSource = new MatTableDataSource<ICliente>(ELEMENT_DATA);
  }

  ngAfterViewInit() {
    if (this.paginator && this.sort) {
      this.dataSource.paginator = this.paginator;
      this.dataSource.sort = this.sort;

    }
  }
}

const ELEMENT_DATA: ICliente[] = [
  {
    id: 1,
    ragioneSociale: 'AAAAA',
    piva: 'string',
    codiceFiscale: 'string',
    codiceSdi: 'string',
    pec: 'string',
    indirizzo: 'string',
    cap: 'string',
    localita: 'string',
    provincia: 'string',
    paese: 'IT',
    telefono: 'string',
    email: 'string',
    destionazioneMerce: 'string',
    agenteRiferimento: 'string',
  },
  {
    id: 2,
    ragioneSociale: 'BBBBBBB',
    piva: 'string',
    codiceFiscale: 'string',
    codiceSdi: 'string',
    pec: 'string',
    indirizzo: 'string',
    cap: 'string',
    localita: 'string',
    provincia: 'string',
    paese: 'IT',
    telefono: 'string',
    email: 'string',
    destionazioneMerce: 'string',
    agenteRiferimento: 'string',
  },
  {
    id: 3,
    ragioneSociale: 'CCCC',
    piva: 'string',
    codiceFiscale: 'string',
    codiceSdi: 'string',
    pec: 'string',
    indirizzo: 'string',
    cap: 'string',
    localita: 'string',
    provincia: 'string',
    paese: 'IT',
    telefono: 'string',
    email: 'string',
    destionazioneMerce: 'string',
    agenteRiferimento: 'string',
  },
  {
    id: 4,
    ragioneSociale: 'DDDDD',
    piva: 'string',
    codiceFiscale: 'string',
    codiceSdi: 'string',
    pec: 'string',
    indirizzo: 'string',
    cap: 'string',
    localita: 'string',
    provincia: 'string',
    paese: 'IT',
    telefono: 'string',
    email: 'string',
    destionazioneMerce: 'string',
    agenteRiferimento: 'string',
  },
  {
    id: 5,
    ragioneSociale: 'EEEEE',
    piva: 'string',
    codiceFiscale: 'string',
    codiceSdi: 'string',
    pec: 'string',
    indirizzo: 'string',
    cap: 'string',
    localita: 'string',
    provincia: 'string',
    paese: 'IT',
    telefono: 'string',
    email: 'string',
    destionazioneMerce: 'string',
    agenteRiferimento: 'string',
  },
  {
    id: 6,
    ragioneSociale: 'Hydrogen',
    piva: 'string',
    codiceFiscale: 'string',
    codiceSdi: 'string',
    pec: 'string',
    indirizzo: 'string',
    cap: 'string',
    localita: 'string',
    provincia: 'string',
    paese: 'IT',
    telefono: 'string',
    email: 'string',
    destionazioneMerce: 'string',
    agenteRiferimento: 'string',
  },
  {
    id: 7,
    ragioneSociale: 'Hydrogen',
    piva: 'string',
    codiceFiscale: 'string',
    codiceSdi: 'string',
    pec: 'string',
    indirizzo: 'string',
    cap: 'string',
    localita: 'string',
    provincia: 'string',
    paese: 'IT',
    telefono: 'string',
    email: 'string',
    destionazioneMerce: 'string',
    agenteRiferimento: 'string',
  },
  {
    id: 8,
    ragioneSociale: 'Hydrogen',
    piva: 'string',
    codiceFiscale: 'string',
    codiceSdi: 'string',
    pec: 'string',
    indirizzo: 'string',
    cap: 'string',
    localita: 'string',
    provincia: 'string',
    paese: 'IT',
    telefono: 'string',
    email: 'string',
    destionazioneMerce: 'string',
    agenteRiferimento: 'string',
  },
  {
    id: 9,
    ragioneSociale: 'Hydrogen',
    piva: 'string',
    codiceFiscale: 'string',
    codiceSdi: 'string',
    pec: 'string',
    indirizzo: 'string',
    cap: 'string',
    localita: 'string',
    provincia: 'string',
    paese: 'IT',
    telefono: 'string',
    email: 'string',
    destionazioneMerce: 'string',
    agenteRiferimento: 'string',
  },
  {
    id: 10,
    ragioneSociale: 'Hydrogen',
    piva: 'string',
    codiceFiscale: 'string',
    codiceSdi: 'string',
    pec: 'string',
    indirizzo: 'string',
    cap: 'string',
    localita: 'string',
    provincia: 'string',
    paese: 'IT',
    telefono: 'string',
    email: 'string',
    destionazioneMerce: 'string',
    agenteRiferimento: 'string',
  },
  {
    id: 11,
    ragioneSociale: 'Hydrogen',
    piva: 'string',
    codiceFiscale: 'string',
    codiceSdi: 'string',
    pec: 'string',
    indirizzo: 'string',
    cap: 'string',
    localita: 'string',
    provincia: 'string',
    paese: 'IT',
    telefono: 'string',
    email: 'string',
    destionazioneMerce: 'string',
    agenteRiferimento: 'string',
  },
  {
    id: 12,
    ragioneSociale: 'Hydrogen',
    piva: 'string',
    codiceFiscale: 'string',
    codiceSdi: 'string',
    pec: 'string',
    indirizzo: 'string',
    cap: 'string',
    localita: 'string',
    provincia: 'string',
    paese: 'IT',
    telefono: 'string',
    email: 'string',
    destionazioneMerce: 'string',
    agenteRiferimento: 'string',
  },
  {
    id: 13,
    ragioneSociale: 'Hydrogen',
    piva: 'string',
    codiceFiscale: 'string',
    codiceSdi: 'string',
    pec: 'string',
    indirizzo: 'string',
    cap: 'string',
    localita: 'string',
    provincia: 'string',
    paese: 'IT',
    telefono: 'string',
    email: 'string',
    destionazioneMerce: 'string',
    agenteRiferimento: 'string',
  },
  {
    id: 14,
    ragioneSociale: 'Hydrogen',
    piva: 'string',
    codiceFiscale: 'string',
    codiceSdi: 'string',
    pec: 'string',
    indirizzo: 'string',
    cap: 'string',
    localita: 'string',
    provincia: 'string',
    paese: 'IT',
    telefono: 'string',
    email: 'string',
    destionazioneMerce: 'string',
    agenteRiferimento: 'string',
  },
  {
    id: 15,
    ragioneSociale: 'Hydrogen',
    piva: 'string',
    codiceFiscale: 'string',
    codiceSdi: 'string',
    pec: 'string',
    indirizzo: 'string',
    cap: 'string',
    localita: 'string',
    provincia: 'string',
    paese: 'IT',
    telefono: 'string',
    email: 'string',
    destionazioneMerce: 'string',
    agenteRiferimento: 'string',
  },
  {
    id: 16,
    ragioneSociale: 'Hydrogen',
    piva: 'string',
    codiceFiscale: 'string',
    codiceSdi: 'string',
    pec: 'string',
    indirizzo: 'string',
    cap: 'string',
    localita: 'string',
    provincia: 'string',
    paese: 'IT',
    telefono: 'string',
    email: 'string',
    destionazioneMerce: 'string',
    agenteRiferimento: 'string',
  },
  {
    id: 17,
    ragioneSociale: 'Hydrogen',
    piva: 'string',
    codiceFiscale: 'string',
    codiceSdi: 'string',
    pec: 'string',
    indirizzo: 'string',
    cap: 'string',
    localita: 'string',
    provincia: 'string',
    paese: 'IT',
    telefono: 'string',
    email: 'string',
    destionazioneMerce: 'string',
    agenteRiferimento: 'string',
  },
  {
    id: 18,
    ragioneSociale: 'Hydrogen',
    piva: 'string',
    codiceFiscale: 'string',
    codiceSdi: 'string',
    pec: 'string',
    indirizzo: 'string',
    cap: 'string',
    localita: 'string',
    provincia: 'string',
    paese: 'IT',
    telefono: 'string',
    email: 'string',
    destionazioneMerce: 'string',
    agenteRiferimento: 'string',
  },
  {
    id: 19,
    ragioneSociale: 'Hydrogen',
    piva: 'string',
    codiceFiscale: 'string',
    codiceSdi: 'string',
    pec: 'string',
    indirizzo: 'string',
    cap: 'string',
    localita: 'string',
    provincia: 'string',
    paese: 'IT',
    telefono: 'string',
    email: 'string',
    destionazioneMerce: 'string',
    agenteRiferimento: 'string',
  },
  {
    id: 20,
    ragioneSociale: 'Hydrogen',
    piva: 'string',
    codiceFiscale: 'string',
    codiceSdi: 'string',
    pec: 'string',
    indirizzo: 'string',
    cap: 'string',
    localita: 'string',
    provincia: 'string',
    paese: 'IT',
    telefono: 'string',
    email: 'string',
    destionazioneMerce: 'string',
    agenteRiferimento: 'string',
  },
];

